[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kurtis-e1"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.15.2",
    "flwr-datasets>=0.5.0",
    "torch==2.3.1",
    "trl==0.8.1",
    "bitsandbytes==0.45.0",
    "scipy==1.13.0",
    "peft==0.14.0",
    "transformers==4.50.2",
    "sentencepiece==0.2.0",
    "omegaconf==2.3.0",
    "hf_transfer==0.1.8",
    "wandb==0.19.8",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "mrs83"

[tool.flwr.app.components]
serverapp = "kurtis_e1.server_app:app"
clientapp = "kurtis_e1.client_app:app"

[tool.flwr.app.config]
use-wandb = true
model.name = "Qwen/Qwen2.5-0.5B-Instruct"
model.quantization = 4
model.gradient-checkpointing = true
model.lora.peft-lora-r = 16
model.lora.peft-lora-alpha = 64
model.lora.peft-use-dora = true
train.save-every-round = 5
train.learning-rate-max = 5e-5
train.learning-rate-min = 1e-6
train.seq-length = 1024
train.training-arguments.output-dir = ""
train.training-arguments.learning-rate = ""
train.training-arguments.per-device-train-batch-size = 16
train.training-arguments.gradient-accumulation-steps = 1
train.training-arguments.logging-steps = 1
train.training-arguments.num-train-epochs = 3
train.training-arguments.max-steps = 6
train.training-arguments.save-steps = 1000
train.training-arguments.save-total-limit = 10
train.training-arguments.gradient-checkpointing = true
train.training-arguments.max-grad-norm = 1.0
train.training-arguments.lr-scheduler-type = "constant"
train.training-arguments.bf16 = true
train.training-arguments.tf32 = true
train.training-arguments.optim = "paged_adamw_8bit"
strategy.fraction-fit = 0.2
strategy.fraction-evaluate = 0.0
num-server-rounds = 100

[tool.flwr.app.config.static]
dataset.name = "ethicalabs/Kurtis-E1-SFT"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 20
options.backend.client-resources.num-cpus = 4
options.backend.client-resources.num-gpus = 1.0
